### ISSUE TITLE
这东西依赖包只有opencl么？

### ISSUE THREAD

**Issue by cgoxopx** [mz24cn/clnet#1]
找了半天，终于找到个支持opencl的

**Comment by cgoxopx** [comment]
想在arm上用。

**Comment by mz24cn** [comment]
是的，零依赖是项目设计之初就定下的目标之一。只依赖OpenCL Driver，目前CPU/GPU都自带opencl驱动（手机上可以下载opencl-z查看GPU的opencl支持情况），所以等于什么额外的依赖都没有。

目前进度是正确性上没有问题，MLP/LSTM/CNN能够在与其他框架在同样的参数下正确收敛到同样的准确率，但CNN/RNN性能方面与cudnn的差距非常大，大概只有几十分之一的性能。

当前的最优先任务就是做opencl kernel的优化，主要是gemm和卷积的winograd FFT优化。不过这些原始版本的kernel仍然保留，适合教学。因为面向硬件高度优化的kernel远没有原始版本的直观好理解。

所以大概还要几个月才能实用化。感谢关注。

**Comment by mz24cn** [comment]
更正：以前的比较有误，性能不会只有几十分之一那么差。错误的把一个三层CNN网络和两层的做比较了。

目前与MXNET自带例子做比较，image-classification，lenet-5（两层CNN+Pooling+两层FC），一个epoch，clNET要**33s**，MXNET要**23s**，**clNET是MXNET 70%的性能**（测试机器GPU是GTX1080，但CPU较差，制约了两者的性能）。

实际使用中，小的多层FC网络一般都能比MXNET跑的快。

**Comment by mz24cn** [comment]
在LSTM的例子中，CharRNN，batchSize取32，embedding_dim取256，MXNET里面的obama语料ipynb例子，GTX1080的性能是**129s**一个epoch，GPU占用率略低于50%；clNET是**110s**一个epoch，GPU占用率不低于96%。**比MXNET略快**。MXNET例子代码可能没使用cuDNN中的LSTM，导致GPU占用率低性能差。

**Comment by mz24cn** [comment]
clNET自身overhead极小，无奈底层opencl不是CUDA的对手，要么没有cuDNN这样高度优化的执行库，要么是硬件自身不行。但CUDA作为一个Proprietary技术，也难以长远支撑Deep Learning持续深入的普及。希望看到OpenCL或其他开源标准在深挖硬件性能上做的更好。
