### ISSUE TITLE
CL_INVALID_EVENT 

### ISSUE THREAD

**Issue by pilipovicr** [mz24cn/clnet#2]
Greetings, 

When I try to run MLP example

sudo ./build/OpenCLNet /nf model MLP

I get an error:

[0,@2019-04-25 17:14:22] GeForce GTX 950M (kernels build: 87ms)
[debugger] interactive thread started on device 0.
[0,0,0ms] error rate: 0.303551
Current Tensor: clnet::type::FullyConnectedLayer: FCLayer_0=sigmoid(l0_weight*X+l0_bias)
Error in device 0: clEnqueueNDRangeKernel (-58): CL_INVALID_EVENT

Output from debugger:

[debugger] device 0 break on IterativeOptimizer: clnet::type::IterativeOptimizer

Greetings 
Ratko

**Comment by pilipovicr** [comment]
Output from debugger:

**Comment by mz24cn** [comment]
sorry, the wrong updates have been corrected. MLP, MLP_softmax, charRNN(LSTM), MNIST_CNN now are resumed to be correct, CIFAR_WRN is in development (on correct short-connection gradient BP behaviours).

**Comment by pilipovicr** [comment]
Thank you for feedback. Now it is working.
